Date:2/01/23

**Practical No.2**

**2.1**

**Aim: Write a numpy program to sort an array by the nth collection**

In [ ]:
import numpy as np
print("Original array:\n")
nums=np.random.randint(0,10,(3,3))
print(nums)
print("In sort the said array by the nth column:")
print(nums[nums[:,1].argsort()])

Original array:

[[2 6 0]
 [1 8 6]
 [6 2 1]]
In sort the said array by the nth column:
[[6 2 1]
 [2 6 0]
 [1 8 6]]


**2.2**

**Aim: Write a numpy program to perform a given array with a specified postion & move all smaller elements value to the left**

In [ ]:
import numpy as np
nums=np.array([70,50,20,12,30,-11,60,40,25,35])
print(nums)
print("\n Alter partitioning on 4th position")
print(np.partition(nums,4))

[ 70  50  20  12  30 -11  60  40  25  35]

 Alter partitioning on 4th position
[ 12 -11  20  25  30  35  60  40  50  70]
