Date:2/1/23

**Practical no.3**

**3.1**

**Aim: Write a numpy program to count a no. of dimensions,no.of elements and no.of bytesfor each element in a given array.** 

In [ ]:
import numpy as np
print("\n Original arrays")
x=np.array([[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,25,22,23]])
print(x)
print("\n Number of dimensions")
print(x.ndim)
print("\n No.of elements")
print(x.size)
print("\n No. of bytes in each elements of given array")
print(x.itemsize)


 Original arrays
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 25 22 23]]

 Number of dimensions
2

 No.of elements
24

 No. of bytes in each elements of given array
8


**3.2**

**Aim: Write a numpy program to get a copy of matrix with the elements below Kth diagonal zero**

In [ ]:
import numpy as np
m=np.matrix([[1,2,3],
            [4,5,6],
            [7,8,9]])
print("matrix given:")
print(m)
print(np.triu(m))
print(np.triu(m,-1))
print(np.triu(m,-2))

matrix given:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1 2 3]
 [4 5 6]
 [0 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
